### ISSUE TITLE
gRPC call return code: 14: Connect Failed

### ISSUE THREAD

**Issue by Huangyz10** [bitnami/bitnami-docker-tensorflow-resnet#1]
**Description**

In the step(Predict an image), 
Into the resnet container,
input>>resnet_client_cc --server_port=model-data_tensorflow-serving_1:8500 --image_file=cat.jpg
output<<gRPC call return code: 14: Connect Failed
**Steps to reproduce the issue:**

1.Run the application using Docker Compose provided
2. move a pic(cat.jpg) into the '/' dir of the resenet container
3. exec into the resnet container,and input>>resnet_client_cc --server_port=model-data_tensorflow-serving_1:8500 --image_file=cat.jpg     #the name of the server container is "model-data_tensorflow-serving_1"

**Describe the results you received:**

<output<<gRPC call return code: 14: Connect Failed>

**Describe the results you expected:**

<>

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(docker desktop community for mac 2.0.4.0 )
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for MAC

**Comment by Huangyz10** [comment]
The ping test between the two container is ok

**Comment by miguelaeh** [comment]
Hi @Huangyz10 ,
Can you detail thoroughly the problem?

**Comment by Huangyz10** [comment]
> Hi @Huangyz10 ,
> Can you detail thoroughly the problem?

Hi, I've edited the issue again. I want predict a pic, but when I input the request command
<resnet_client_cc ***>, I only get a "grpc connected failed " reply.

**Comment by miguelaeh** [comment]
Hi @Huangyz10 ,
I can get your error if I don't configure the Resnet model.
Try to do do this before run the image (in your local):
```
$ mkdir /tmp/model-data
$ cd /tmp/model-data
$ wget 'http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz'
$ tar xzf resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz --strip-components=2
```
That will install the Resnet model into the container and after that you should not get the error.

**Comment by Huangyz10** [comment]
> Hi @Huangyz10 ,
> I can get your error if I don't configure the Resnet model.
> Try to do do this before run the image (in your local):
> 
> ```
> $ mkdir /tmp/model-data
> $ cd /tmp/model-data
> $ wget 'http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz'
> $ tar xzf resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz --strip-components=2
> ```
> 
> That will install the Resnet model into the container and after that you should not get the error.


Thanks! Your suggestions are right, It's ok now.

I find my errors stems from the '$ tar xzf resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz --strip-components=2'
I tar the gz manually, copy the 'pb and variables' into the model-data dir. which leads to '--strip-components=3'.

**Comment by miguelaeh** [comment]
I am glad it worked!
Feel free to ask again if you need help.
