### ISSUE TITLE
Install TensorFlow Resnet in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-tensorflow-resnet#2]
Are you a data scientist using the IBM Cloud? Well, this documentation is for you. It will guide you on how to install TensorFlow Resnet on the IBM Cloud using the Kubernetes Service. Simple and effective so you can start programming with it.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105617572-046e6080-5dad-11eb-9e6c-127c6df28d4c.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105617687-33d19d00-5dae-11eb-95f2-447ad63eb4ad.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105617688-39c77e00-5dae-11eb-8f3a-5f73226b942a.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105617689-4055f580-5dae-11eb-8807-6924a574cba2.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105617692-451aa980-5dae-11eb-95e5-dfb1f225c7bb.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105617695-49df5d80-5dae-11eb-9adf-bdd5755a0705.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105617699-519f0200-5dae-11eb-97ac-fa1fcf9bff6b.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105617798-31237780-5daf-11eb-90f5-87bba689973e.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105617794-2963d300-5daf-11eb-815e-a7f7fb4babc5.PNG)

## Step 3: Install TensorFlow Resnet

* Click on the search section at the top of the main page, type TensorFlow Resnet, and click on it.

![tensor1](https://user-images.githubusercontent.com/70336951/105617724-88751800-5dae-11eb-8918-e31c969a959b.PNG)

* A new window opens, select the cluster, and then select the workspace you want TensorFlow Resnet to be installed. You can also write a new workspace. In this case, we will use the previously _storage-example_ workspace. Type a workspace name under 'Configure your workspace', accept the terms and click on Install. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/tensorflow-resnet "here").

![tensor3](https://user-images.githubusercontent.com/70336951/105617728-8e6af900-5dae-11eb-88fc-347eada7d4d1.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105617735-97f46100-5dae-11eb-92a5-31f45999013c.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105617742-9dea4200-5dae-11eb-8c9b-6ccae5b0e4a3.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105617745-a3e02300-5dae-11eb-9c23-2aa5ff714713.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105617748-a8a4d700-5dae-11eb-8412-f4680666246e.PNG)

* Once you have installed the terminal, click on the action button again, select web terminal, and type the following command. It will show you the workspaces of your cluster. You can see *tensorflow-example* is now active.

`$ kubectl get ns`

![tensortest0](https://user-images.githubusercontent.com/70336951/105617753-b2c6d580-5dae-11eb-8b3d-42559ffffd5b.png)

* You can then obtain more data about the service and it's pods. You can now use the External IP and its port to call the TensowFlow Resnet model in your own application.

`$ kubectl get pod -n NAMESERVICE -o wide`

![tensortest2](https://user-images.githubusercontent.com/70336951/105617759-db4ecf80-5dae-11eb-826f-dcf19e5db3b6.PNG)

`$ kubectl get service -n NAME SERVICE`

![tensortest3](https://user-images.githubusercontent.com/70336951/105617761-e0ac1a00-5dae-11eb-9ddb-1ee675945d9f.PNG)

* Select the pod within your service using bash if you want to use the files or change any configuration of the TensorFlow installation.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![tensortest4](https://user-images.githubusercontent.com/70336951/105617764-ebff4580-5dae-11eb-974a-ab48d9aef66a.PNG)

You have finished the installation, enjoy your TensorFlow Resnet installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as "Closed" so it can be used by other users looking for information as if it were documentation
